# Generated by Django 5.2.8 on 2025-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('deporte', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('costos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoria', models.CharField(choices=[('Femenil', 'Femenil'), ('Varonil', 'Varonil'), ('Mixto', 'Mixto')], max_length=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Finalizada', 'Finalizada')], default='Abierta', max_length=20)),
            ],
        ),
    ]
