# Generated by Django 5.2.8 on 2025-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='id',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='ID_convocatoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='arbitraje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='bases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='cómite_organizador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='datos_de_contacto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='descripción',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='inscripciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='junta_previa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='normatividad_aplicable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='pie_de_pagina',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='premiación',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='rama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='sistema_de_competencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='transitorios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
