# Generated by Django 5.2.8 on 2026-01-09 16:31

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_remove_convocatoria_id_convocatoria_id_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-fecha_inicio_torneo'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.RenameField(
            model_name='convocatoria',
            old_name='bases',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='convocatoria',
            old_name='datos_de_contacto',
            new_name='junta_previa_descripcion',
        ),
        migrations.RenameField(
            model_name='convocatoria',
            old_name='cómite_organizador',
            new_name='premiacion_primero',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='ID_convocatoria',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='costos',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='descripción',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='inscripciones',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='junta_previa',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='pie_de_pagina',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='premiación',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='sistema_de_competencia',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='comite_organizador',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='costo_arbitraje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo en pesos', max_digits=10),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='direccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='documentos_requeridos',
            field=models.TextField(blank=True, help_text='Lista de documentos necesarios', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fase_final',
            field=models.TextField(blank=True, help_text='Descripción de la fase final', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_inicio_torneo',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de inicio del torneo'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_limite_inscripcion',
            field=models.DateField(default=datetime.date.today, help_text='Fecha límite para inscripciones'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_reunion_previa',
            field=models.DateField(blank=True, help_text='Fecha de reunión previa', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='forma_pago',
            field=models.TextField(blank=True, help_text='Descripción de formas de pago', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='hora_reunion_previa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la convocatoria', null=True, upload_to='convocatorias/fondos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='institucion_responsable',
            field=models.CharField(default='Instituto Municipal de Cultura Física y Deporte', max_length=300),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='junta_previa_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='junta_previa_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='logo_ayuntamiento',
            field=models.ImageField(blank=True, help_text='Logo del ayuntamiento (parte superior). Tamaño recomendado: 300x150px', null=True, upload_to='convocatorias/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='lugar_inscripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='premiacion_adicional',
            field=models.TextField(blank=True, help_text='Otros premios', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='premiacion_segundo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='premiacion_tercero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='sistema_competencia',
            field=models.TextField(blank=True, help_text='Formato del torneo (round-robin, eliminatoria, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='arbitraje',
            field=models.TextField(blank=True, help_text='Información sobre árbitros', null=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Juvenil', 'Juvenil'), ('Veteranos', 'Veteranos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('En curso', 'En curso'), ('Finalizada', 'Finalizada')], default='Abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la liga/torneo', max_length=200),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='normatividad_aplicable',
            field=models.TextField(blank=True, help_text='Reglamentos aplicables', null=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='rama',
            field=models.CharField(choices=[('Femenil', 'Femenil'), ('Varonil', 'Varonil'), ('Mixta', 'Mixta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Requisitos para participar', null=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='transitorios',
            field=models.TextField(blank=True, help_text='Disposiciones transitorias', null=True),
        ),
    ]
